- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql_setup.yaml


- name: start and enable systemctl
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started

- name: creating user and password  
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"

  
